{{- if eq .Values.serving.type "predictive" }}
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  annotations:
    opendatahub.io/connections: {{ .Values.name }}
    opendatahub.io/model-type: predictive
    openshift.io/display-name: {{ .Values.name }}
    security.opendatahub.io/enable-auth: '{{ .Values.auth.enabled }}'
    serving.kserve.io/deploymentMode: RawDeployment
    opendatahub.io/hardware-profile-name: {{ .Values.serving.hardwareProfile.name | quote }}
    opendatahub.io/hardware-profile-namespace: {{ .Values.serving.hardwareProfile.namespace | quote }}
  labels:
    opendatahub.io/dashboard: "true"
    networking.kserve.io/visibility: exposed
    {{- if .Values.kueue.localQueueName }}
    kueue.x-k8s.io/queue-name: {{ .Values.kueue.localQueueName | quote }}
    {{- end }}
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    # imagePullSecrets:
    #   - name: {{ .Values.name }}
    minReplicas: {{ .Values.replicas }}
    maxReplicas: {{ .Values.replicas }}
    {{- if and (eq (include "rhoai-serving.hasNvidiaGpu" . | trim) "true") .Values.serving.gpuPodTolerations }}
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
    {{- end }}
    model:
      modelFormat:
        name: {{ .Values.runtime.modelFormat.name }}
        version: "{{ .Values.runtime.modelFormat.version }}"
      runtime: {{ .Values.name }}
      storageUri: {{ .Values.model.uri }}
      resources:
        {{- include "rhoai-serving.kserveModelResources" . | nindent 8 }}
{{- end }}
