{{- if and (eq .Values.serving.type "predictive") (eq .Values.scaling.mode "keda") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-keda-sa
  namespace: {{ include "rhoai-serving.namespaceName" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-keda-sa-token
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}-keda-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-thanos-metrics-reader
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-thanos-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}-thanos-metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-keda-sa
    namespace: {{ include "rhoai-serving.namespaceName" . }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.name }}-keda-trigger-auth-prometheus
  namespace: {{ include "rhoai-serving.namespaceName" . }}
spec:
  secretTargetRef:
    - parameter: bearerToken
      name: {{ .Values.name }}-keda-sa-token
      key: token
    - parameter: ca
      name: {{ .Values.name }}-keda-sa-token
      key: ca.crt
{{- end }}
