{{- if eq .Values.serving.type "generative" }}
---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  annotations:
    openshift.io/display-name: {{ .Values.name }}
    opendatahub.io/connections: {{ .Values.name }}
    opendatahub.io/genai-use-case: chat
    security.opendatahub.io/enable-auth: '{{ .Values.auth.enabled }}'
    opendatahub.io/model-type: generative
    {{- if .Values.serving.hardwareProfile.name }}
    opendatahub.io/hardware-profile-name: {{ .Values.serving.hardwareProfile.name | quote }}
    opendatahub.io/hardware-profile-namespace: {{ .Values.serving.hardwareProfile.namespace | quote }}
    {{- end }}
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
    {{- if .Values.kueue.localQueueName }}
    kueue.x-k8s.io/queue-name: {{ .Values.kueue.localQueueName | quote }}
    {{- end }}

spec:

  # Model specification
  model:
    uri: {{ .Values.model.uri }}
    name: {{ .Values.model.name }}
    criticality: Critical

  router:
    {{- if .Values.routerGatewayRefs }}
    gateway:
      refs:
        {{- toYaml .Values.routerGatewayRefs | nindent 8 }}
    {{- else }}
    gateway: {}
    {{- end }}
    route: {}
    scheduler: {}

  # Multi-node workload with data parallelism
  # parallelism:
  #   tensor: 4
  #   data: 8
  #   dataLocal: 4

  # Decode workload (main)
  replicas: {{ .Values.replicas }}
  template:
    containers:
      - name: main
        {{- if .Values.mainContainer.image }}
        image: {{ .Values.mainContainer.image | quote }}
        {{- end }}
        {{- with .Values.mainContainer.command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.mainContainer.args }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if or .Values.extraArgs .Values.extraEnv .Values.hfToken }}
        env:
          {{- if .Values.hfToken }}
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-secret
                key: HF_TOKEN
          {{- end }}
          {{- if .Values.extraArgs }}
          - name: VLLM_ADDITIONAL_ARGS
            value: {{ join " " .Values.extraArgs | quote }}
          {{- end }}
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
        resources:
          {{- include "rhoai-serving.kserveModelResources" . | nindent 10 }}
    {{- if and (eq (include "rhoai-serving.hasNvidiaGpu" . | trim) "true") .Values.serving.gpuPodTolerations }}
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
    {{- end }}
{{- end }}
