{{- if .Values.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "rhoai-serving.namespaceName" . }}
  annotations:
    openshift.io/display-name: {{ include "rhoai-serving.namespaceDisplayName" . | quote }}
    openshift.io/description: {{ include "rhoai-serving.namespaceDescription" . | quote }}
  labels:
    opendatahub.io/dashboard: 'true'
    rhoai-serving/model: 'true'
    {{- if .Values.namespace.kueueManaged }}
    kueue.openshift.io/managed: 'true'
    {{- end }}
    {{- if and (eq .Values.serving.type "predictive") (eq .Values.scaling.mode "keda") .Values.monitoring.userWorkloadDisabled }}
    openshift.io/cluster-monitoring: 'true'
    {{- end }}
{{- end }}
