---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/description: ''
    openshift.io/display-name: {{ .Values.name }}
stringData:
  URI: {{ .Values.model.uri }}
type: Opaque
