{{- if eq (include "rhoai-serving.useHfToken" . | trim) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-secret
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  labels:
    opendatahub.io/dashboard: "true"
type: Opaque
stringData:
  HF_TOKEN: {{ .Values.hfToken }}
{{- end }}
