{{- if and (eq .Values.serving.type "generative") .Values.guardrails.enabled (eq .Values.guardrails.type "nemo") }}
---
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  name: {{ .Values.name }}-nemo-guardrails
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  labels:
    app: {{ .Values.name }}-nemo-guardrails
  annotations:
    security.opendatahub.io/enable-auth: 'true'
spec:
  nemoConfigs:
    - name: nemo-config
      configMaps:
        - {{ .Values.name }}-nemo-config
  env:
    - name: "OPENAI_API_KEY"
      valueFrom:
        secretKeyRef:
          name: {{ .Values.name }}-sa-token
          key: "token"
    # Use OpenShift service CA bundle for internal gateway HTTPS
    - name: "SSL_CERT_FILE"
      value: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
{{- end }}
