{{- if and (eq .Values.serving.type "generative") .Values.guardrails.enabled (eq .Values.guardrails.type "nemo") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-nemo-guardrails-view
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  labels:
    app: {{ .Values.name }}-nemo-guardrails
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-nemo-guardrails
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
{{- end }}
