{{- if and (eq .Values.serving.type "generative") .Values.guardrails.enabled (eq .Values.guardrails.type "nemo") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-nemo-guardrails-sa-token
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  labels:
    app: {{ .Values.name }}-nemo-guardrails
    opendatahub.io/dashboard: "true"
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}-nemo-guardrails
    openshift.io/display-name: {{ .Values.name }}-nemo-guardrails
type: kubernetes.io/service-account-token
{{- end }}
