{{- if and (eq .Values.serving.type "generative") .Values.guardrails.enabled .Values.guardrails.guardLlm.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-guard-token
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  labels:
    app: {{ .Values.name }}-nemo-guardrails
type: Opaque
data:
  token: {{ .Values.guardrails.guardLlm.token | b64enc }}
{{- end }}
