{{- if and (eq .Values.serving.type "generative") .Values.guardrails.enabled (eq .Values.guardrails.type "nemo") .Values.guardrails.nemo.modelToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-nemo-api-token
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  labels:
    app: {{ .Values.name }}-nemo-guardrails
type: Opaque
stringData:
  token: {{ .Values.guardrails.nemo.modelToken | quote }}
{{- end }}
