{{- if and (eq .Values.serving.type "generative") .Values.guardrails.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-nemo-guardrails
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  labels:
    app: {{ .Values.name }}-nemo-guardrails
{{- end }}
