{{- if and (eq .Values.serving.type "predictive") (eq .Values.scaling.mode "keda") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-keda-sa-token
  namespace: {{ include "rhoai-serving.namespaceName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}-keda-sa
type: kubernetes.io/service-account-token
{{- end }}
