{{- if and (eq .Values.serving.type "predictive") (eq .Values.scaling.mode "keda") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-keda-sa
  namespace: {{ include "rhoai-serving.namespaceName" . }}
{{- end }}
